apiVersion: v1
kind: Service
metadata:
  name: customer-frontend-service
spec:
  type: NodePort
  selector:
    app: customer-frontend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-frontend
  template:
    metadata:
      labels:
        app: customer-frontend
    spec:
      nodeSelector:
        app: customer
      containers:
      - name: customer-frontend
        image: chungjm0711/take-it-customer-frontend-amd64:3.8
        env:
        - name: VUE_APP_CUSTOMER_GATEWAY_URL
          value: http://customer-gateway-service.default.svc.cluster.local:8000
        ports:
        - containerPort: 8080