apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: chungjm0711/take-it-order-svc-amd64:3.0
        env:
        - name: spring.datasource.url
          value: jdbc:mariadb://order-db-service.default.svc.cluster.local:3306/notificationdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        - name: kafka.host
          value: kafka-service.default.svc.cluster.local
        - name: spring.zipkin.base-url
          value: http://jaeger-collector.istio-system.svc.cluster.local:9411
        ports:
        - containerPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order
  ports:
  - port: 9200
    targetPort: 9200