apiVersion: v1
kind: Service
metadata:
  name: owner-frontend-service
  labels:
    app: owner-frontend
spec:
  type: NodePort
  selector:
    app: owner
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: owner
  name: owner-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: owner
  template:
    metadata:
      labels:
        app: owner
    spec:
      containers:
      - image: chungjm0711/take-it-owner-frontend-amd64:3.3
        name: owner-frontend
        env:
        - name: VUE_APP_OWNER_API_GATEWAY_URL
          value: http://owner-gateway-service.default.svc.cluster.local:8001
        ports:
        - containerPort: 8081