apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
      - name: store
        image: chungjm0711/take-it-store-svc-amd64:3.0
        env:
        - name: spring.datasource.url
          value: jdbc:mariadb://store-db-service.default.svc.cluster.local:3306/storedb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        - name: spring.zipkin.base-url
          value: http://jaeger-collector.istio-system.svc.cluster.local:9411
        ports:
        - containerPort: 9300
---
apiVersion: v1
kind: Service
metadata:
  name: store-service
spec:
  selector:
    app: store
  ports:
  - port: 9300
    targetPort: 9300