apiVersion: v1
kind: Service
metadata:
  name: notification-db-service
spec:
  selector:
    app: notification-db
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-db
spec:
  selector:
    matchLabels:
      app: notification-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: notification-db
    spec:
      containers:
      - image: chungjm0711/take-it-mariadb-amd64:1.0
        name: noti-mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: password
        ports:
        - containerPort: 3306
          name: noti-mariadb
        volumeMounts:
        - name: efs-pvc
          mountPath: "/mnt"
      volumes:
      - name: efs-pvc
        hostPath:
          path: /noti
          type: DirectoryOrCreate