apiVersion: v1
kind: Service
metadata:
  name: user-db-service
spec:
  selector:
    app: user-db
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
spec:
  selector:
    matchLabels:
      app: user-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
      - image: chungjm0711/take-it-mariadb-amd64:1.0
        name: user-mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: password
        args:
        - --character-set-server=utf8
        - --collation-server=utf8_unicode_ci
        ports:
        - containerPort: 3306
          name: user-mariadb
        volumeMounts:
        - name: efs-pvc
          mountPath: "/mnt"
      volumes:
      - name: efs-pvc
        hostPath:
          path: /user
          type: DirectoryOrCreate